INSERT INTO EMPLOYEE VALUES (1, 'SAM','SAM@SAM.COM',123456);

INSERT INTO STUDENT VALUES (101,'JIN', 'PRAGRA');
INSERT INTO STUDENT VALUES (102,'TIM', 'XYZ');
INSERT INTO STUDENT VALUES (103,'SAM', 'ABC');
INSERT INTO STUDENT VALUES (104,'KIM', 'RTS');